name: Build docker image

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v4

    - name: Install prerequisites
      run: sudo apt-get update
    - run: sudo apt-get install -qq -y wget make ca-certificates git

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.22'

    - name: Set up docker environment variables
      run: echo 'DOCKER_OPTS="-H tcp://127.0.0.1:2375 -H unix:///var/run/docker.sock -s devicemapper"' | sudo tee /etc/default/docker > /dev/null

    - name: Run tests
      run: make test

    - name: Build image
      run: make docker-image

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Push image
      run: make docker-push
